/* tslint:disable */
/* eslint-disable */
/**
 * Meta OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Document,
  KnowledgeChunk,
  Memory,
} from '../models/index';
import {
    DocumentFromJSON,
    DocumentToJSON,
    KnowledgeChunkFromJSON,
    KnowledgeChunkToJSON,
    MemoryFromJSON,
    MemoryToJSON,
} from '../models/index';

export interface DeleteDocumentRequest {
    memory: string;
    document: string;
}

export interface ListDocumentsRequest {
    memory: string;
}

export interface SearchKbRequest {
    memory: string;
    q: string;
    tag?: Array<string>;
}

export interface SubmitDocumentRequest {
    memory: string;
    document: string;
    document2?: Document;
}

/**
 * 
 */
export class KbApi extends runtime.BaseAPI {

    /**
     * deletes all the knowledge chunks identified by a specific file name
     */
    async deleteDocumentRaw(requestParameters: DeleteDocumentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['memory'] == null) {
            throw new runtime.RequiredError(
                'memory',
                'Required parameter "memory" was null or undefined when calling deleteDocument().'
            );
        }

        if (requestParameters['document'] == null) {
            throw new runtime.RequiredError(
                'document',
                'Required parameter "document" was null or undefined when calling deleteDocument().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/kb/{memory}/documents/{document}`;
        urlPath = urlPath.replace(`{${"memory"}}`, encodeURIComponent(String(requestParameters['memory'])));
        urlPath = urlPath.replace(`{${"document"}}`, encodeURIComponent(String(requestParameters['document'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * deletes all the knowledge chunks identified by a specific file name
     */
    async deleteDocument(requestParameters: DeleteDocumentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteDocumentRaw(requestParameters, initOverrides);
    }

    /**
     * lists all the documents in a memory slot
     */
    async listDocumentsRaw(requestParameters: ListDocumentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        if (requestParameters['memory'] == null) {
            throw new runtime.RequiredError(
                'memory',
                'Required parameter "memory" was null or undefined when calling listDocuments().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/kb/{memory}/documents`;
        urlPath = urlPath.replace(`{${"memory"}}`, encodeURIComponent(String(requestParameters['memory'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * lists all the documents in a memory slot
     */
    async listDocuments(requestParameters: ListDocumentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.listDocumentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * lists all the knowledge base memory slots, and their available tags
     */
    async listKbMemoriesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: Memory; }>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/kb/_memories`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => runtime.mapValues(jsonValue, MemoryFromJSON));
    }

    /**
     * lists all the knowledge base memory slots, and their available tags
     */
    async listKbMemories(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: Memory; }> {
        const response = await this.listKbMemoriesRaw(initOverrides);
        return await response.value();
    }

    /**
     * searches knowledge chunks in a memory slot
     */
    async searchKbRaw(requestParameters: SearchKbRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<KnowledgeChunk>>> {
        if (requestParameters['memory'] == null) {
            throw new runtime.RequiredError(
                'memory',
                'Required parameter "memory" was null or undefined when calling searchKb().'
            );
        }

        if (requestParameters['q'] == null) {
            throw new runtime.RequiredError(
                'q',
                'Required parameter "q" was null or undefined when calling searchKb().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['tag'] != null) {
            queryParameters['tag'] = requestParameters['tag'];
        }

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/kb/{memory}`;
        urlPath = urlPath.replace(`{${"memory"}}`, encodeURIComponent(String(requestParameters['memory'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(KnowledgeChunkFromJSON));
    }

    /**
     * searches knowledge chunks in a memory slot
     */
    async searchKb(requestParameters: SearchKbRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<KnowledgeChunk>> {
        const response = await this.searchKbRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * submits a new document to a memory slot
     */
    async submitDocumentRaw(requestParameters: SubmitDocumentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['memory'] == null) {
            throw new runtime.RequiredError(
                'memory',
                'Required parameter "memory" was null or undefined when calling submitDocument().'
            );
        }

        if (requestParameters['document'] == null) {
            throw new runtime.RequiredError(
                'document',
                'Required parameter "document" was null or undefined when calling submitDocument().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/kb/{memory}/documents/{document}`;
        urlPath = urlPath.replace(`{${"memory"}}`, encodeURIComponent(String(requestParameters['memory'])));
        urlPath = urlPath.replace(`{${"document"}}`, encodeURIComponent(String(requestParameters['document'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DocumentToJSON(requestParameters['document2']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * submits a new document to a memory slot
     */
    async submitDocument(requestParameters: SubmitDocumentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.submitDocumentRaw(requestParameters, initOverrides);
    }

}
