/* tslint:disable */
/* eslint-disable */
/**
 * Meta OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DataObject,
} from '../models/index';
import {
    DataObjectFromJSON,
    DataObjectToJSON,
} from '../models/index';

export interface CreateObjectRequest {
    memory: string;
    dataObject?: DataObject;
}

export interface DeleteObjectByNameRequest {
    memory: string;
    name: string;
}

export interface GetObjectByNameRequest {
    memory: string;
    name: string;
}

export interface ListObjectsRequest {
    memory: string;
}

/**
 * 
 */
export class ObjectsApi extends runtime.BaseAPI {

    /**
     */
    async createObjectRaw(requestParameters: CreateObjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['memory'] == null) {
            throw new runtime.RequiredError(
                'memory',
                'Required parameter "memory" was null or undefined when calling createObject().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/objects/{memory}`;
        urlPath = urlPath.replace(`{${"memory"}}`, encodeURIComponent(String(requestParameters['memory'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DataObjectToJSON(requestParameters['dataObject']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createObject(requestParameters: CreateObjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createObjectRaw(requestParameters, initOverrides);
    }

    /**
     */
    async deleteObjectByNameRaw(requestParameters: DeleteObjectByNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['memory'] == null) {
            throw new runtime.RequiredError(
                'memory',
                'Required parameter "memory" was null or undefined when calling deleteObjectByName().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling deleteObjectByName().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/objects/{memory}/_by-name`;
        urlPath = urlPath.replace(`{${"memory"}}`, encodeURIComponent(String(requestParameters['memory'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteObjectByName(requestParameters: DeleteObjectByNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteObjectByNameRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getObjectByNameRaw(requestParameters: GetObjectByNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataObject>> {
        if (requestParameters['memory'] == null) {
            throw new runtime.RequiredError(
                'memory',
                'Required parameter "memory" was null or undefined when calling getObjectByName().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling getObjectByName().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/objects/{memory}/_by-name`;
        urlPath = urlPath.replace(`{${"memory"}}`, encodeURIComponent(String(requestParameters['memory'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataObjectFromJSON(jsonValue));
    }

    /**
     */
    async getObjectByName(requestParameters: GetObjectByNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataObject> {
        const response = await this.getObjectByNameRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async listObjectsRaw(requestParameters: ListObjectsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DataObject>>> {
        if (requestParameters['memory'] == null) {
            throw new runtime.RequiredError(
                'memory',
                'Required parameter "memory" was null or undefined when calling listObjects().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/objects/{memory}`;
        urlPath = urlPath.replace(`{${"memory"}}`, encodeURIComponent(String(requestParameters['memory'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DataObjectFromJSON));
    }

    /**
     */
    async listObjects(requestParameters: ListObjectsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DataObject>> {
        const response = await this.listObjectsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async listObjectsMemoriesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/objects/_memories`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async listObjectsMemories(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.listObjectsMemoriesRaw(initOverrides);
        return await response.value();
    }

}
