/* tslint:disable */
/* eslint-disable */
/**
 * Meta OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Memory,
  Recipe,
  RecipeRequest,
} from '../models/index';
import {
    MemoryFromJSON,
    MemoryToJSON,
    RecipeFromJSON,
    RecipeToJSON,
    RecipeRequestFromJSON,
    RecipeRequestToJSON,
} from '../models/index';

export interface CreateRecipeRequest {
    memory: string;
    recipeRequest?: RecipeRequest;
}

export interface DeleteRecipeRequest {
    memory: string;
    recipeId: string;
}

export interface SearchRecipesRequest {
    memory: string;
    tag?: Array<string>;
    q?: string;
}

export interface UpdateRecipeRequest {
    memory: string;
    recipeId: string;
    recipeRequest?: RecipeRequest;
}

/**
 * 
 */
export class RecipesApi extends runtime.BaseAPI {

    /**
     * creates a new recipe in a memory slot
     */
    async createRecipeRaw(requestParameters: CreateRecipeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Recipe>> {
        if (requestParameters['memory'] == null) {
            throw new runtime.RequiredError(
                'memory',
                'Required parameter "memory" was null or undefined when calling createRecipe().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/recipes/{memory}`;
        urlPath = urlPath.replace(`{${"memory"}}`, encodeURIComponent(String(requestParameters['memory'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RecipeRequestToJSON(requestParameters['recipeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecipeFromJSON(jsonValue));
    }

    /**
     * creates a new recipe in a memory slot
     */
    async createRecipe(requestParameters: CreateRecipeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Recipe> {
        const response = await this.createRecipeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * deletes a specific recipe
     */
    async deleteRecipeRaw(requestParameters: DeleteRecipeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['memory'] == null) {
            throw new runtime.RequiredError(
                'memory',
                'Required parameter "memory" was null or undefined when calling deleteRecipe().'
            );
        }

        if (requestParameters['recipeId'] == null) {
            throw new runtime.RequiredError(
                'recipeId',
                'Required parameter "recipeId" was null or undefined when calling deleteRecipe().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/recipes/{memory}/{recipeId}`;
        urlPath = urlPath.replace(`{${"memory"}}`, encodeURIComponent(String(requestParameters['memory'])));
        urlPath = urlPath.replace(`{${"recipeId"}}`, encodeURIComponent(String(requestParameters['recipeId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * deletes a specific recipe
     */
    async deleteRecipe(requestParameters: DeleteRecipeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteRecipeRaw(requestParameters, initOverrides);
    }

    /**
     * lists all the recipes memory slots, and their available tags
     */
    async listRecipesMemoriesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: Memory; }>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/recipes/_memories`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => runtime.mapValues(jsonValue, MemoryFromJSON));
    }

    /**
     * lists all the recipes memory slots, and their available tags
     */
    async listRecipesMemories(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: Memory; }> {
        const response = await this.listRecipesMemoriesRaw(initOverrides);
        return await response.value();
    }

    /**
     * searches recipes in a memory slot
     */
    async searchRecipesRaw(requestParameters: SearchRecipesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Recipe>>> {
        if (requestParameters['memory'] == null) {
            throw new runtime.RequiredError(
                'memory',
                'Required parameter "memory" was null or undefined when calling searchRecipes().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['tag'] != null) {
            queryParameters['tag'] = requestParameters['tag'];
        }

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/recipes/{memory}`;
        urlPath = urlPath.replace(`{${"memory"}}`, encodeURIComponent(String(requestParameters['memory'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RecipeFromJSON));
    }

    /**
     * searches recipes in a memory slot
     */
    async searchRecipes(requestParameters: SearchRecipesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Recipe>> {
        const response = await this.searchRecipesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * updates a specific recipe
     */
    async updateRecipeRaw(requestParameters: UpdateRecipeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Recipe>> {
        if (requestParameters['memory'] == null) {
            throw new runtime.RequiredError(
                'memory',
                'Required parameter "memory" was null or undefined when calling updateRecipe().'
            );
        }

        if (requestParameters['recipeId'] == null) {
            throw new runtime.RequiredError(
                'recipeId',
                'Required parameter "recipeId" was null or undefined when calling updateRecipe().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/recipes/{memory}/{recipeId}`;
        urlPath = urlPath.replace(`{${"memory"}}`, encodeURIComponent(String(requestParameters['memory'])));
        urlPath = urlPath.replace(`{${"recipeId"}}`, encodeURIComponent(String(requestParameters['recipeId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RecipeRequestToJSON(requestParameters['recipeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecipeFromJSON(jsonValue));
    }

    /**
     * updates a specific recipe
     */
    async updateRecipe(requestParameters: UpdateRecipeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Recipe> {
        const response = await this.updateRecipeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
