/* tslint:disable */
/* eslint-disable */
/**
 * Meta OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DataObject
 */
export interface DataObject {
    /**
     * 
     * @type {string}
     * @memberof DataObject
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof DataObject
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof DataObject
     */
    contentType?: DataObjectContentTypeEnum;
}


/**
 * @export
 */
export const DataObjectContentTypeEnum = {
    TextPlain: 'text/plain',
    ApplicationJson: 'application/json',
    TextMarkdown: 'text/markdown'
} as const;
export type DataObjectContentTypeEnum = typeof DataObjectContentTypeEnum[keyof typeof DataObjectContentTypeEnum];


/**
 * Check if a given object implements the DataObject interface.
 */
export function instanceOfDataObject(value: object): value is DataObject {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function DataObjectFromJSON(json: any): DataObject {
    return DataObjectFromJSONTyped(json, false);
}

export function DataObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataObject {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'content': json['content'],
        'contentType': json['content_type'] == null ? undefined : json['content_type'],
    };
}

export function DataObjectToJSON(json: any): DataObject {
    return DataObjectToJSONTyped(json, false);
}

export function DataObjectToJSONTyped(value?: DataObject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'content': value['content'],
        'content_type': value['contentType'],
    };
}

