/* tslint:disable */
/* eslint-disable */
/**
 * Meta OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KnowledgeChunk
 */
export interface KnowledgeChunk {
    /**
     * 
     * @type {string}
     * @memberof KnowledgeChunk
     */
    document: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof KnowledgeChunk
     */
    tags: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof KnowledgeChunk
     */
    chunk: string;
}

/**
 * Check if a given object implements the KnowledgeChunk interface.
 */
export function instanceOfKnowledgeChunk(value: object): value is KnowledgeChunk {
    if (!('document' in value) || value['document'] === undefined) return false;
    if (!('tags' in value) || value['tags'] === undefined) return false;
    if (!('chunk' in value) || value['chunk'] === undefined) return false;
    return true;
}

export function KnowledgeChunkFromJSON(json: any): KnowledgeChunk {
    return KnowledgeChunkFromJSONTyped(json, false);
}

export function KnowledgeChunkFromJSONTyped(json: any, ignoreDiscriminator: boolean): KnowledgeChunk {
    if (json == null) {
        return json;
    }
    return {
        
        'document': json['document'],
        'tags': json['tags'],
        'chunk': json['chunk'],
    };
}

export function KnowledgeChunkToJSON(json: any): KnowledgeChunk {
    return KnowledgeChunkToJSONTyped(json, false);
}

export function KnowledgeChunkToJSONTyped(value?: KnowledgeChunk | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'document': value['document'],
        'tags': value['tags'],
        'chunk': value['chunk'],
    };
}

