/* tslint:disable */
/* eslint-disable */
/**
 * Meta OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Memory
 */
export interface Memory {
    /**
     * 
     * @type {Array<string>}
     * @memberof Memory
     */
    availableTags: Array<string>;
}

/**
 * Check if a given object implements the Memory interface.
 */
export function instanceOfMemory(value: object): value is Memory {
    if (!('availableTags' in value) || value['availableTags'] === undefined) return false;
    return true;
}

export function MemoryFromJSON(json: any): Memory {
    return MemoryFromJSONTyped(json, false);
}

export function MemoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): Memory {
    if (json == null) {
        return json;
    }
    return {
        
        'availableTags': json['available_tags'],
    };
}

export function MemoryToJSON(json: any): Memory {
    return MemoryToJSONTyped(json, false);
}

export function MemoryToJSONTyped(value?: Memory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'available_tags': value['availableTags'],
    };
}

