/* tslint:disable */
/* eslint-disable */
/**
 * Meta OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelObject
 */
export interface ModelObject {
    /**
     * 
     * @type {string}
     * @memberof ModelObject
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ModelObject
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof ModelObject
     */
    contentType?: ModelObjectContentTypeEnum;
}


/**
 * @export
 */
export const ModelObjectContentTypeEnum = {
    TextPlain: 'text/plain',
    ApplicationJson: 'application/json',
    TextMarkdown: 'text/markdown'
} as const;
export type ModelObjectContentTypeEnum = typeof ModelObjectContentTypeEnum[keyof typeof ModelObjectContentTypeEnum];


/**
 * Check if a given object implements the ModelObject interface.
 */
export function instanceOfModelObject(value: object): value is ModelObject {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function ModelObjectFromJSON(json: any): ModelObject {
    return ModelObjectFromJSONTyped(json, false);
}

export function ModelObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelObject {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'content': json['content'],
        'contentType': json['content_type'] == null ? undefined : json['content_type'],
    };
}

export function ModelObjectToJSON(json: any): ModelObject {
    return ModelObjectToJSONTyped(json, false);
}

export function ModelObjectToJSONTyped(value?: ModelObject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'content': value['content'],
        'content_type': value['contentType'],
    };
}

