/* tslint:disable */
/* eslint-disable */
/**
 * Meta OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Recipe
 */
export interface Recipe {
    /**
     * 
     * @type {string}
     * @memberof Recipe
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Recipe
     */
    tags: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Recipe
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof Recipe
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof Recipe
     */
    id: string;
}

/**
 * Check if a given object implements the Recipe interface.
 */
export function instanceOfRecipe(value: object): value is Recipe {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('tags' in value) || value['tags'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function RecipeFromJSON(json: any): Recipe {
    return RecipeFromJSONTyped(json, false);
}

export function RecipeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Recipe {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'tags': json['tags'],
        'description': json['description'],
        'content': json['content'],
        'id': json['id'],
    };
}

export function RecipeToJSON(json: any): Recipe {
    return RecipeToJSONTyped(json, false);
}

export function RecipeToJSONTyped(value?: Recipe | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'tags': value['tags'],
        'description': value['description'],
        'content': value['content'],
        'id': value['id'],
    };
}

