/* tslint:disable */
/* eslint-disable */
/**
 * Meta OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecipeRequest
 */
export interface RecipeRequest {
    /**
     * 
     * @type {string}
     * @memberof RecipeRequest
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof RecipeRequest
     */
    tags: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof RecipeRequest
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof RecipeRequest
     */
    content: string;
}

/**
 * Check if a given object implements the RecipeRequest interface.
 */
export function instanceOfRecipeRequest(value: object): value is RecipeRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('tags' in value) || value['tags'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function RecipeRequestFromJSON(json: any): RecipeRequest {
    return RecipeRequestFromJSONTyped(json, false);
}

export function RecipeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'tags': json['tags'],
        'description': json['description'],
        'content': json['content'],
    };
}

export function RecipeRequestToJSON(json: any): RecipeRequest {
    return RecipeRequestToJSONTyped(json, false);
}

export function RecipeRequestToJSONTyped(value?: RecipeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'tags': value['tags'],
        'description': value['description'],
        'content': value['content'],
    };
}

