// Package dto provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package dto

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Document defines model for document.
type Document struct {
	Content string   `json:"content"`
	Tags    []string `json:"tags"`
}

// KnowledgeChunk defines model for knowledge_chunk.
type KnowledgeChunk struct {
	Chunk    string   `json:"chunk"`
	Document string   `json:"document"`
	Tags     []string `json:"tags"`
}

// KnowledgeChunks defines model for knowledge_chunks.
type KnowledgeChunks = []KnowledgeChunk

// Memories defines model for memories.
type Memories map[string]Memory

// Memory defines model for memory.
type Memory struct {
	AvailableTags []string `json:"available_tags"`
}

// Recipe defines model for recipe.
type Recipe struct {
	Content     string             `json:"content"`
	Description string             `json:"description"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
	Tags        []string           `json:"tags"`
}

// RecipeRequest defines model for recipe_request.
type RecipeRequest struct {
	Content     string   `json:"content"`
	Description string   `json:"description"`
	Name        string   `json:"name"`
	Tags        []string `json:"tags"`
}

// Recipes defines model for recipes.
type Recipes = []Recipe

// SearchKbParams defines parameters for SearchKb.
type SearchKbParams struct {
	Tag *[]string `form:"tag,omitempty" json:"tag,omitempty"`
	Q   string    `form:"q" json:"q"`
}

// SearchRecipesParams defines parameters for SearchRecipes.
type SearchRecipesParams struct {
	Tag *[]string `form:"tag,omitempty" json:"tag,omitempty"`
	Q   *string   `form:"q,omitempty" json:"q,omitempty"`
}

// SubmitDocumentJSONRequestBody defines body for SubmitDocument for application/json ContentType.
type SubmitDocumentJSONRequestBody = Document

// CreateRecipeJSONRequestBody defines body for CreateRecipe for application/json ContentType.
type CreateRecipeJSONRequestBody = RecipeRequest

// UpdateRecipeJSONRequestBody defines body for UpdateRecipe for application/json ContentType.
type UpdateRecipeJSONRequestBody = RecipeRequest
