// Package webserver provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package webserver

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
	. "github.com/theirish81/meta/internal/dto"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /kb/_memories)
	ListKbMemories(ctx echo.Context) error

	// (GET /kb/{memory})
	SearchKb(ctx echo.Context, memory string, params SearchKbParams) error

	// (GET /kb/{memory}/documents)
	ListDocuments(ctx echo.Context, memory string) error

	// (DELETE /kb/{memory}/documents/{document})
	DeleteDocument(ctx echo.Context, memory string, document string) error

	// (POST /kb/{memory}/documents/{document})
	SubmitDocument(ctx echo.Context, memory string, document string) error

	// (GET /recipes/_memories)
	ListRecipesMemories(ctx echo.Context) error

	// (GET /recipes/{memory})
	SearchRecipes(ctx echo.Context, memory string, params SearchRecipesParams) error

	// (POST /recipes/{memory})
	CreateRecipe(ctx echo.Context, memory string) error

	// (DELETE /recipes/{memory}/{recipeId})
	DeleteRecipe(ctx echo.Context, memory string, recipeId openapi_types.UUID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListKbMemories converts echo context to params.
func (w *ServerInterfaceWrapper) ListKbMemories(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListKbMemories(ctx)
	return err
}

// SearchKb converts echo context to params.
func (w *ServerInterfaceWrapper) SearchKb(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "memory" -------------
	var memory string

	err = runtime.BindStyledParameterWithOptions("simple", "memory", ctx.Param("memory"), &memory, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter memory: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchKbParams
	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameter("form", true, false, "tag", ctx.QueryParams(), &params.Tag)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tag: %s", err))
	}

	// ------------- Required query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, true, "q", ctx.QueryParams(), &params.Q)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter q: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SearchKb(ctx, memory, params)
	return err
}

// ListDocuments converts echo context to params.
func (w *ServerInterfaceWrapper) ListDocuments(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "memory" -------------
	var memory string

	err = runtime.BindStyledParameterWithOptions("simple", "memory", ctx.Param("memory"), &memory, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter memory: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListDocuments(ctx, memory)
	return err
}

// DeleteDocument converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteDocument(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "memory" -------------
	var memory string

	err = runtime.BindStyledParameterWithOptions("simple", "memory", ctx.Param("memory"), &memory, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter memory: %s", err))
	}

	// ------------- Path parameter "document" -------------
	var document string

	err = runtime.BindStyledParameterWithOptions("simple", "document", ctx.Param("document"), &document, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter document: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteDocument(ctx, memory, document)
	return err
}

// SubmitDocument converts echo context to params.
func (w *ServerInterfaceWrapper) SubmitDocument(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "memory" -------------
	var memory string

	err = runtime.BindStyledParameterWithOptions("simple", "memory", ctx.Param("memory"), &memory, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter memory: %s", err))
	}

	// ------------- Path parameter "document" -------------
	var document string

	err = runtime.BindStyledParameterWithOptions("simple", "document", ctx.Param("document"), &document, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter document: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SubmitDocument(ctx, memory, document)
	return err
}

// ListRecipesMemories converts echo context to params.
func (w *ServerInterfaceWrapper) ListRecipesMemories(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListRecipesMemories(ctx)
	return err
}

// SearchRecipes converts echo context to params.
func (w *ServerInterfaceWrapper) SearchRecipes(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "memory" -------------
	var memory string

	err = runtime.BindStyledParameterWithOptions("simple", "memory", ctx.Param("memory"), &memory, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter memory: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchRecipesParams
	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameter("form", true, false, "tag", ctx.QueryParams(), &params.Tag)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tag: %s", err))
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, false, "q", ctx.QueryParams(), &params.Q)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter q: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SearchRecipes(ctx, memory, params)
	return err
}

// CreateRecipe converts echo context to params.
func (w *ServerInterfaceWrapper) CreateRecipe(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "memory" -------------
	var memory string

	err = runtime.BindStyledParameterWithOptions("simple", "memory", ctx.Param("memory"), &memory, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter memory: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateRecipe(ctx, memory)
	return err
}

// DeleteRecipe converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteRecipe(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "memory" -------------
	var memory string

	err = runtime.BindStyledParameterWithOptions("simple", "memory", ctx.Param("memory"), &memory, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter memory: %s", err))
	}

	// ------------- Path parameter "recipeId" -------------
	var recipeId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "recipeId", ctx.Param("recipeId"), &recipeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter recipeId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteRecipe(ctx, memory, recipeId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/kb/_memories", wrapper.ListKbMemories)
	router.GET(baseURL+"/kb/:memory", wrapper.SearchKb)
	router.GET(baseURL+"/kb/:memory/documents", wrapper.ListDocuments)
	router.DELETE(baseURL+"/kb/:memory/documents/:document", wrapper.DeleteDocument)
	router.POST(baseURL+"/kb/:memory/documents/:document", wrapper.SubmitDocument)
	router.GET(baseURL+"/recipes/_memories", wrapper.ListRecipesMemories)
	router.GET(baseURL+"/recipes/:memory", wrapper.SearchRecipes)
	router.POST(baseURL+"/recipes/:memory", wrapper.CreateRecipe)
	router.DELETE(baseURL+"/recipes/:memory/:recipeId", wrapper.DeleteRecipe)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8RXQW/iOhD+K2jeO+Y1bd+ecttdLlW3arV7rBBy7AFcEtu1HboVyn9f2U5SEgKEFroX",
	"FDme8XzfN5+HrIHKXEmBwhpI1mDoAnPiH5mkRY7CumelpUJtOfo3VApbvbCvCiEBYzUXcygjsGTu93CL",
	"uenfERaI1uQVyjICjc8F18ggeQzhUXPCpNku0yek1sUvhXzJkM1xSheFWPaUVy9vHb0J6dSVN7mjBoSv",
	"YwCE9rH/apxBAv/Eb8rElSxxF/tWURHkmEtdMUEY45ZLQbKHFkP7jvDxAV71uEUwWRGekTTD6Qc56yTq",
	"o0oj5W5pDSTL7meQPO4vP+yfulPQuAzd4jlzvzOpc2IhgaLgDKJu3Z06OYNJubu65rSjnMLQUM2V06f3",
	"vSA5ntFiPn27iv2+C1iH92ql3HY5ZQRczKSvnNvMvbpDS0b3CsXXhxuIYIXaeFpgdeUSSIWCKA4J/H9x",
	"eXENEShiF76CeJnG082en6On26lAHKobBgn84Mbepnf1NgfGKClMCLm+vOyIRZTKOPXx8ZMJAgVcg+zj",
	"zvA4Wxo31hwRjSONttACmdcnSPoIy9RR//s/pAtpkPpOLQSt4ikRU42EhdwO+TpYtNwJ/BcSTRe3qadM",
	"kxwtauNNxF1GR2PdC0nt9812sbrAaAP6lk+qRM8F+sgqkyVz2Awb3qr9+Z6PKmryQX3fcxWb/kZvN0AT",
	"Mwoxp2+EuB5D+70wbnadqS9OJsGhhtniuCHgnOTG6/rRW49hhha3qR779fHbP4MOJ19CcH+LcDMKeY8t",
	"/kVziz7mrJZvJ2KbII/oEiVN37VVpDm343ZONPabZK8nu6qbkssyzMiWNlcHtCG0Qvk+cVxrVRN14Pz6",
	"GXb//SFmycjh3e2v+p/CcJPVTAycZxUVOy6vT5hF57v4Dv+j2q3KiQQ530joN/t3jcRi0PRMVu9+Few0",
	"/AlP2ykTNyPqIb9LpL4LpBlQ67BywwaMpYbwT5wSdXl7Ux36NpsMmaM1030j9FimywgM6lVNUKEzSCAm",
	"isfu82TSJF63YRr/9VktLVMoJ+WfAAAA///rVigcbxEAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
