// Package webserver provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package webserver

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
	. "github.com/theirish81/meta/internal/dto"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /kb/_memories)
	ListKbMemories(ctx echo.Context) error

	// (GET /kb/{memory})
	SearchKb(ctx echo.Context, memory string, params SearchKbParams) error

	// (GET /kb/{memory}/documents)
	ListDocuments(ctx echo.Context, memory string) error

	// (DELETE /kb/{memory}/documents/{document})
	DeleteDocument(ctx echo.Context, memory string, document string) error

	// (POST /kb/{memory}/documents/{document})
	SubmitDocument(ctx echo.Context, memory string, document string) error

	// (GET /objects/_memories)
	ListObjectsMemories(ctx echo.Context) error

	// (GET /objects/{memory})
	ListObjects(ctx echo.Context, memory string) error

	// (POST /objects/{memory})
	CreateObject(ctx echo.Context, memory string) error

	// (DELETE /objects/{memory}/_by-name)
	DeleteObjectByName(ctx echo.Context, memory string, params DeleteObjectByNameParams) error

	// (GET /objects/{memory}/_by-name)
	GetObjectByName(ctx echo.Context, memory string, params GetObjectByNameParams) error

	// (GET /recipes/_memories)
	ListRecipesMemories(ctx echo.Context) error

	// (GET /recipes/{memory})
	SearchRecipes(ctx echo.Context, memory string, params SearchRecipesParams) error

	// (POST /recipes/{memory})
	CreateRecipe(ctx echo.Context, memory string) error

	// (DELETE /recipes/{memory}/{recipeId})
	DeleteRecipe(ctx echo.Context, memory string, recipeId openapi_types.UUID) error

	// (POST /recipes/{memory}/{recipeId})
	UpdateRecipe(ctx echo.Context, memory string, recipeId openapi_types.UUID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListKbMemories converts echo context to params.
func (w *ServerInterfaceWrapper) ListKbMemories(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListKbMemories(ctx)
	return err
}

// SearchKb converts echo context to params.
func (w *ServerInterfaceWrapper) SearchKb(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "memory" -------------
	var memory string

	err = runtime.BindStyledParameterWithOptions("simple", "memory", ctx.Param("memory"), &memory, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter memory: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchKbParams
	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameter("form", true, false, "tag", ctx.QueryParams(), &params.Tag)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tag: %s", err))
	}

	// ------------- Required query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, true, "q", ctx.QueryParams(), &params.Q)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter q: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SearchKb(ctx, memory, params)
	return err
}

// ListDocuments converts echo context to params.
func (w *ServerInterfaceWrapper) ListDocuments(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "memory" -------------
	var memory string

	err = runtime.BindStyledParameterWithOptions("simple", "memory", ctx.Param("memory"), &memory, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter memory: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListDocuments(ctx, memory)
	return err
}

// DeleteDocument converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteDocument(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "memory" -------------
	var memory string

	err = runtime.BindStyledParameterWithOptions("simple", "memory", ctx.Param("memory"), &memory, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter memory: %s", err))
	}

	// ------------- Path parameter "document" -------------
	var document string

	err = runtime.BindStyledParameterWithOptions("simple", "document", ctx.Param("document"), &document, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter document: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteDocument(ctx, memory, document)
	return err
}

// SubmitDocument converts echo context to params.
func (w *ServerInterfaceWrapper) SubmitDocument(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "memory" -------------
	var memory string

	err = runtime.BindStyledParameterWithOptions("simple", "memory", ctx.Param("memory"), &memory, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter memory: %s", err))
	}

	// ------------- Path parameter "document" -------------
	var document string

	err = runtime.BindStyledParameterWithOptions("simple", "document", ctx.Param("document"), &document, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter document: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SubmitDocument(ctx, memory, document)
	return err
}

// ListObjectsMemories converts echo context to params.
func (w *ServerInterfaceWrapper) ListObjectsMemories(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListObjectsMemories(ctx)
	return err
}

// ListObjects converts echo context to params.
func (w *ServerInterfaceWrapper) ListObjects(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "memory" -------------
	var memory string

	err = runtime.BindStyledParameterWithOptions("simple", "memory", ctx.Param("memory"), &memory, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter memory: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListObjects(ctx, memory)
	return err
}

// CreateObject converts echo context to params.
func (w *ServerInterfaceWrapper) CreateObject(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "memory" -------------
	var memory string

	err = runtime.BindStyledParameterWithOptions("simple", "memory", ctx.Param("memory"), &memory, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter memory: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateObject(ctx, memory)
	return err
}

// DeleteObjectByName converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteObjectByName(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "memory" -------------
	var memory string

	err = runtime.BindStyledParameterWithOptions("simple", "memory", ctx.Param("memory"), &memory, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter memory: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteObjectByNameParams
	// ------------- Required query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, true, "name", ctx.QueryParams(), &params.Name)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteObjectByName(ctx, memory, params)
	return err
}

// GetObjectByName converts echo context to params.
func (w *ServerInterfaceWrapper) GetObjectByName(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "memory" -------------
	var memory string

	err = runtime.BindStyledParameterWithOptions("simple", "memory", ctx.Param("memory"), &memory, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter memory: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetObjectByNameParams
	// ------------- Required query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, true, "name", ctx.QueryParams(), &params.Name)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetObjectByName(ctx, memory, params)
	return err
}

// ListRecipesMemories converts echo context to params.
func (w *ServerInterfaceWrapper) ListRecipesMemories(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListRecipesMemories(ctx)
	return err
}

// SearchRecipes converts echo context to params.
func (w *ServerInterfaceWrapper) SearchRecipes(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "memory" -------------
	var memory string

	err = runtime.BindStyledParameterWithOptions("simple", "memory", ctx.Param("memory"), &memory, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter memory: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchRecipesParams
	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameter("form", true, false, "tag", ctx.QueryParams(), &params.Tag)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tag: %s", err))
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, false, "q", ctx.QueryParams(), &params.Q)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter q: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SearchRecipes(ctx, memory, params)
	return err
}

// CreateRecipe converts echo context to params.
func (w *ServerInterfaceWrapper) CreateRecipe(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "memory" -------------
	var memory string

	err = runtime.BindStyledParameterWithOptions("simple", "memory", ctx.Param("memory"), &memory, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter memory: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateRecipe(ctx, memory)
	return err
}

// DeleteRecipe converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteRecipe(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "memory" -------------
	var memory string

	err = runtime.BindStyledParameterWithOptions("simple", "memory", ctx.Param("memory"), &memory, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter memory: %s", err))
	}

	// ------------- Path parameter "recipeId" -------------
	var recipeId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "recipeId", ctx.Param("recipeId"), &recipeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter recipeId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteRecipe(ctx, memory, recipeId)
	return err
}

// UpdateRecipe converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateRecipe(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "memory" -------------
	var memory string

	err = runtime.BindStyledParameterWithOptions("simple", "memory", ctx.Param("memory"), &memory, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter memory: %s", err))
	}

	// ------------- Path parameter "recipeId" -------------
	var recipeId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "recipeId", ctx.Param("recipeId"), &recipeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter recipeId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateRecipe(ctx, memory, recipeId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/kb/_memories", wrapper.ListKbMemories)
	router.GET(baseURL+"/kb/:memory", wrapper.SearchKb)
	router.GET(baseURL+"/kb/:memory/documents", wrapper.ListDocuments)
	router.DELETE(baseURL+"/kb/:memory/documents/:document", wrapper.DeleteDocument)
	router.POST(baseURL+"/kb/:memory/documents/:document", wrapper.SubmitDocument)
	router.GET(baseURL+"/objects/_memories", wrapper.ListObjectsMemories)
	router.GET(baseURL+"/objects/:memory", wrapper.ListObjects)
	router.POST(baseURL+"/objects/:memory", wrapper.CreateObject)
	router.DELETE(baseURL+"/objects/:memory/_by-name", wrapper.DeleteObjectByName)
	router.GET(baseURL+"/objects/:memory/_by-name", wrapper.GetObjectByName)
	router.GET(baseURL+"/recipes/_memories", wrapper.ListRecipesMemories)
	router.GET(baseURL+"/recipes/:memory", wrapper.SearchRecipes)
	router.POST(baseURL+"/recipes/:memory", wrapper.CreateRecipe)
	router.DELETE(baseURL+"/recipes/:memory/:recipeId", wrapper.DeleteRecipe)
	router.POST(baseURL+"/recipes/:memory/:recipeId", wrapper.UpdateRecipe)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xZ32/bNhD+Vwhuj2rldHvSW7tgQ9Z1KdYNewgCgxLPNmuJVEjKiWHofx9IivphSbac",
	"2Mleilgkj999d9+dTt3hRGS54MC1wtEOq2QFGbF/UqLJbfwdEm1+5VLkIDUDu5YIroHbBb3NAUdYacn4",
	"EpeBX5u7hR2msCBFqnGENTzpME8J4zjAwIsMR3fdhyTPU5YQzQQPvythHtn1jMg1FY8c3wf9CznJYABJ",
	"GWAJDwWTQM09dleNrmVIOB/LAFORFFnl1nR/NVnaPUxDpoZ3uAdESrLt4bLHD+Nac/GYAl3CPFkVfD0A",
	"zz/uXd126dzIa9tB7YTFMcGF7rU/SljgCP8QNrkYVokY7vveAxXgDDIhKyYIpcxkD0m/dhg6dIU979yr",
	"/uwRTDaEpSROYf5CzvYMDVElIWFOOSRNbxc4ujsM3+2fm1tAGQv74Bk1/y6EzIhRYVEwioMjamEU35fj",
	"6OrbTlIKBZVIlpv4DK6PCPlcEqsqQBvFYd05X6fnahW5ITgKkkIyvf1mtjqTMRAJ8mOhV82vX32Qfv/3",
	"bxy4amwMudUmaiutc1waw4wvhGWE6dSsfAFN0G0O/OPXGxzgDUhl6cabKwNM5MBJznCEf3o/e/8BBzgn",
	"emXxhOs4nLe1tATt6ncrajhlSitE0hTpFaBanSgmCpCTD1Kp0CpAhFOziUlUZz2qQmEyxlb5G4oj/AdT",
	"+nP8xV9tiFe54MrB+DCb7SVWr0vUjWuS1M0dlruuZ34NEQlIgi4kB2qD59LvDq9jkyZP7yBZCQWJVVXB",
	"k+p8QvhcAqHOtmFz5/goR8lUQGSyAtXi0ZVHxDgibTp7nH2zRz/HNoKSZKBBKlsrmLFsoupTPvJlra0K",
	"LQsIWqz1ykFl6KEAe7KypMkSt49NV+SwvYeTQN1fMDV6HWogRXphOnuqhL6pTlVgvf94yhiZXdfmL5Q3",
	"Lw3R5ITqBadh4oJRCXf+z9JFJgUN/Ri550N10uubAtdswYCieIsIUjkkbMEStGApoKpTdcN3bW1eNy9d",
	"ezz/3IfRXMsUcphOJeRRMg32zEXLTNcQbTt5QublQg1V2SLOmEkLxOGxFgzS4liJteeuu1hA6U+Cbs9W",
	"dmpXy9K9tvS1cyCmJKnYeV5QTZq71x012Pr79cMNhOpcvfr5aj/erSvHTlC8p2Kgb48ycTYGDiZJM4pP",
	"oKZy41zMXK5ReLl2yf1FAtFQuXsh0bX4HJLdVV92jjOjucTiexajQ7qre8w83r7zE1DTV4Z6gIP+afun",
	"axPH+0ADfqgJnAg+GNbEb6AP45pdKHzBqLP/3+QfeRvmnrjJIjKZVI2pJw9v1bmXTG1/ORNvP7ppYkGO",
	"1zw/y0/vBp7W6VOcJ3Ti8FaRN/Im/gqD19sMWj4SY3E8Uwgv37a62F1b8G+ZDuvxTHDNzmXChZrd/vfB",
	"0YZ3xttGgzvSPyeGtt0/9+UZ7tyTGzptMmtGLunZH+q1rdAc67LewaEee6KDrzpted4Omjr2+XhUF0VO",
	"yTTC/7E731wLs1fUgiPnZVpofV22qdL+rnxnP+IrkBufSIVMcYRDkrNwc4XtJ353766bDsr+R0L1aB23",
	"f/k3qPK+/C8AAP//5u1rSz8cAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
